server.port=8081
spring.application.name=agentiabtc
spring.ai.ollama.chat.model=llama3.1

spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp
telegram.api.key=++++++++++++++++
telegram.bot.username=ThiernoAgentAI_Bot

